# Generated by Django 2.0.6 on 2018-06-04 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Leave empty to generate a UUID', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-_.]+$', 'Only [0-9a-zA-Z-_.] characters are allowed')])),
                ('description', models.CharField(blank=True, max_length=256)),
                ('listable', models.BooleanField(default=True, help_text='Uncheck this option to hide the container from the listing')),
                ('requires_auth', models.BooleanField(default=False, help_text='Check this opetion to make the container available to authenticated users only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SFTMFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-_.]+$', 'Only [0-9a-zA-Z-_.] characters are allowed')])),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sendfilestome.Container')),
            ],
            options={
                'verbose_name': 'file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='sftmfile',
            unique_together={('name', 'container')},
        ),
    ]
