# Generated by Django 2.0.6 on 2018-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendfilestome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='requires_auth',
            field=models.BooleanField(default=False, help_text='Check this option to make the container available to authenticated users only'),
        ),
    ]
