# Generated by Django 2.0.6 on 2019-03-05 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendfilestome', '0002_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(blank=True, help_text='Leave empty to generate a random name (UUID)', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-_.]+$', 'Only [0-9a-zA-Z-_.] characters are allowed')]),
        ),
    ]
